// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"time"
)

// Defines values for CourseLevel.
const (
	A1 CourseLevel = "A1"
	A2 CourseLevel = "A2"
	B1 CourseLevel = "B1"
	B2 CourseLevel = "B2"
	C1 CourseLevel = "C1"
	C2 CourseLevel = "C2"
)

// Valid indicates whether the value is a known member of the CourseLevel enum.
func (e CourseLevel) Valid() bool {
	switch e {
	case A1:
		return true
	case A2:
		return true
	case B1:
		return true
	case B2:
		return true
	case C1:
		return true
	case C2:
		return true
	default:
		return false
	}
}

// Defines values for CourseStatus.
const (
	Draft     CourseStatus = "draft"
	Published CourseStatus = "published"
)

// Valid indicates whether the value is a known member of the CourseStatus enum.
func (e CourseStatus) Valid() bool {
	switch e {
	case Draft:
		return true
	case Published:
		return true
	default:
		return false
	}
}

// Defines values for ErrorCode.
const (
	ErrorCodeConflict        ErrorCode = "conflict"
	ErrorCodeForbidden       ErrorCode = "forbidden"
	ErrorCodeInternalError   ErrorCode = "internal_error"
	ErrorCodeMalformedBody   ErrorCode = "malformed_body"
	ErrorCodeNotFound        ErrorCode = "not_found"
	ErrorCodeRateLimited     ErrorCode = "rate_limited"
	ErrorCodeUnauthorized    ErrorCode = "unauthorized"
	ErrorCodeValidationError ErrorCode = "validation_error"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case ErrorCodeConflict:
		return true
	case ErrorCodeForbidden:
		return true
	case ErrorCodeInternalError:
		return true
	case ErrorCodeMalformedBody:
		return true
	case ErrorCodeNotFound:
		return true
	case ErrorCodeRateLimited:
		return true
	case ErrorCodeUnauthorized:
		return true
	case ErrorCodeValidationError:
		return true
	default:
		return false
	}
}

// Defines values for UserRole.
const (
	Admin   UserRole = "admin"
	Student UserRole = "student"
)

// Valid indicates whether the value is a known member of the UserRole enum.
func (e UserRole) Valid() bool {
	switch e {
	case Admin:
		return true
	case Student:
		return true
	default:
		return false
	}
}

// Defines values for VocabularyReviewRequestGrade.
const (
	Forgot     VocabularyReviewRequestGrade = "forgot"
	Remembered VocabularyReviewRequestGrade = "remembered"
)

// Valid indicates whether the value is a known member of the VocabularyReviewRequestGrade enum.
func (e VocabularyReviewRequestGrade) Valid() bool {
	switch e {
	case Forgot:
		return true
	case Remembered:
		return true
	default:
		return false
	}
}

// Defines values for VocabularyState.
const (
	Due      VocabularyState = "due"
	Learning VocabularyState = "learning"
	Mastered VocabularyState = "mastered"
)

// Valid indicates whether the value is a known member of the VocabularyState enum.
func (e VocabularyState) Valid() bool {
	switch e {
	case Due:
		return true
	case Learning:
		return true
	case Mastered:
		return true
	default:
		return false
	}
}

// Course defines model for Course.
type Course struct {
	CoverImageUrl *string   `json:"cover_image_url"`
	CreatedAt     time.Time `json:"created_at"`
	Description   string    `json:"description"`
	Id            string    `json:"id"`

	// Level Trình độ theo khung CEFR.
	Level CourseLevel `json:"level"`

	// Slug Example: ngu-phap-co-ban
	Slug string `json:"slug"`

	// Status Trạng thái xuất bản.
	Status CourseStatus `json:"status"`

	// Title Example: Ngữ pháp cơ bản
	Title     string    `json:"title"`
	UpdatedAt time.Time `json:"updated_at"`
}

// CourseCreate defines model for CourseCreate.
type CourseCreate struct {
	CoverImageUrl *string `json:"cover_image_url,omitempty"`
	Description   *string `json:"description,omitempty"`

	// Level Trình độ theo khung CEFR.
	Level CourseLevel `json:"level"`
	Slug  string      `json:"slug"`

	// Status Trạng thái xuất bản.
	Status *CourseStatus `json:"status,omitempty"`
	Title  string        `json:"title"`
}

// CourseLevel Trình độ theo khung CEFR.
type CourseLevel string

// CourseList defines model for CourseList.
type CourseList struct {
	Items []Course `json:"items"`

	// NextCursor Con trỏ cho trang kế tiếp; `null` nghĩa là đã hết.
	NextCursor *string `json:"next_cursor"`
}

// CourseProgress defines model for CourseProgress.
type CourseProgress struct {
	CompletedCount int64  `json:"completed_count"`
	CourseId       string `json:"course_id"`

	// LessonCount Tổng số bài chưa xoá của khoá — mẫu số của tỉ lệ.
	LessonCount int64 `json:"lesson_count"`
}

// CourseStatus Trạng thái xuất bản.
type CourseStatus string

// CourseUpdate defines model for CourseUpdate.
type CourseUpdate struct {
	CoverImageUrl *string `json:"cover_image_url,omitempty"`
	Description   *string `json:"description,omitempty"`

	// Level Trình độ theo khung CEFR.
	Level *CourseLevel `json:"level,omitempty"`
	Slug  *string      `json:"slug,omitempty"`

	// Status Trạng thái xuất bản.
	Status *CourseStatus `json:"status,omitempty"`
	Title  *string       `json:"title,omitempty"`
}

// DayActivity defines model for DayActivity.
type DayActivity struct {
	CompletedLessons int64  `json:"completed_lessons"`
	Date             string `json:"date"`
}

// Error defines model for Error.
type Error struct {
	Code ErrorCode `json:"code"`

	// Details Lỗi theo từng field, chỉ có với validation_error.
	Details *map[string]string `json:"details,omitempty"`

	// Message Câu thông báo tiếng Việt, hiển thị được cho người dùng.
	Message string `json:"message"`
}

// ErrorCode defines model for Error.Code.
type ErrorCode string

// GoogleSignInRequest defines model for GoogleSignInRequest.
type GoogleSignInRequest struct {
	// Code Authorization code Google trả về.
	Code string `json:"code"`

	// RedirectUri Đúng redirect_uri đã dùng ở bước chuyển hướng.
	RedirectUri string `json:"redirect_uri"`
}

// Lesson defines model for Lesson.
type Lesson struct {
	CourseId  string    `json:"course_id"`
	CreatedAt time.Time `json:"created_at"`
	Id        string    `json:"id"`
	Position  int32     `json:"position"`
	Slug      string    `json:"slug"`
	Title     string    `json:"title"`
	UpdatedAt time.Time `json:"updated_at"`
}

// LessonCreate defines model for LessonCreate.
type LessonCreate struct {
	Slug  string `json:"slug"`
	Title string `json:"title"`
}

// LessonList defines model for LessonList.
type LessonList struct {
	Items []Lesson `json:"items"`
}

// LessonOrder defines model for LessonOrder.
type LessonOrder struct {
	// LessonIds Toàn bộ id bài của khoá, theo thứ tự mong muốn.
	LessonIds []string `json:"lesson_ids"`
}

// LessonUpdate defines model for LessonUpdate.
type LessonUpdate struct {
	Slug  *string `json:"slug,omitempty"`
	Title *string `json:"title,omitempty"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// ProgressSnapshot defines model for ProgressSnapshot.
type ProgressSnapshot struct {
	// CompletedLessonIds Id các bài đã đánh dấu xong, mới nhất trước.
	CompletedLessonIds []string         `json:"completed_lesson_ids"`
	Courses            []CourseProgress `json:"courses"`

	// GoalXp Mục tiêu XP mỗi ngày.
	GoalXp int64 `json:"goal_xp"`

	// LatestCourseId Khoá được học gần đây nhất; `null` khi chưa học bài nào.
	LatestCourseId *string `json:"latest_course_id"`

	// StreakDays Số ngày học liên tiếp. Vẫn giữ nguyên khi hôm nay chưa học nhưng
	// hôm qua có — người học còn nguyên hôm nay để nối tiếp.
	StreakDays int64 `json:"streak_days"`

	// TodayXp XP đã đạt hôm nay, tính theo giờ Việt Nam.
	TodayXp int64 `json:"today_xp"`

	// Week Bảy ngày gần nhất, cũ trước mới sau; ngày không học vẫn có mặt.
	Week []DayActivity `json:"week"`

	// XpPerLesson XP cho mỗi bài hoàn thành. Có mặt để phía trước cộng trừ được ngay
	// khi người học bấm, mà không phải viết cứng lại con số của server.
	XpPerLesson int64 `json:"xp_per_lesson"`
}

// RefreshRequest defines model for RefreshRequest.
type RefreshRequest struct {
	RefreshToken string `json:"refresh_token"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	DisplayName string `json:"display_name"`
	Email       string `json:"email"`

	// Password Tối thiểu 12 ký tự.
	Password string `json:"password"`
}

// TokenPair defines model for TokenPair.
type TokenPair struct {
	// AccessToken JWT HS256 dùng cho header Authorization.
	AccessToken string `json:"access_token"`

	// ExpiresIn Số giây còn hiệu lực của access token.
	ExpiresIn int64 `json:"expires_in"`

	// RefreshToken Chuỗi mờ, chỉ dùng được một lần.
	RefreshToken string `json:"refresh_token"`
	User         User   `json:"user"`
}

// User defines model for User.
type User struct {
	CreatedAt   time.Time `json:"created_at"`
	DisplayName string    `json:"display_name"`
	Email       string    `json:"email"`
	Id          string    `json:"id"`
	Role        UserRole  `json:"role"`
}

// UserRole defines model for UserRole.
type UserRole string

// VocabularyCard defines model for VocabularyCard.
type VocabularyCard struct {
	Entry VocabularyEntry `json:"entry"`

	// Familiarity Số đốt sáng trên vạch 5 đốt.
	Familiarity int32 `json:"familiarity"`

	// Level Trình độ theo khung CEFR.
	Level CourseLevel `json:"level"`

	// Review `null` khi người học chưa ôn từ này lần nào.
	Review *VocabularyReview `json:"review"`

	// State `due` đến hạn ôn (kể cả từ chưa ôn lần nào), `learning` đang học,
	// `mastered` khoảng cách ôn đã từ 21 ngày trở lên.
	State VocabularyState `json:"state"`
}

// VocabularyCardList defines model for VocabularyCardList.
type VocabularyCardList struct {
	Items []VocabularyCard `json:"items"`
}

// VocabularyEntry defines model for VocabularyEntry.
type VocabularyEntry struct {
	CreatedAt time.Time `json:"created_at"`
	Example   string    `json:"example"`
	ExampleVi string    `json:"example_vi"`
	Id        string    `json:"id"`
	Ipa       string    `json:"ipa"`
	LessonId  string    `json:"lesson_id"`
	Meaning   string    `json:"meaning"`
	Position  int32     `json:"position"`
	UpdatedAt time.Time `json:"updated_at"`
	Word      string    `json:"word"`
}

// VocabularyEntryCreate defines model for VocabularyEntryCreate.
type VocabularyEntryCreate struct {
	Example   *string `json:"example,omitempty"`
	ExampleVi *string `json:"example_vi,omitempty"`
	Ipa       *string `json:"ipa,omitempty"`
	LessonId  string  `json:"lesson_id"`
	Meaning   string  `json:"meaning"`
	Word      string  `json:"word"`
}

// VocabularyEntryList defines model for VocabularyEntryList.
type VocabularyEntryList struct {
	Items []VocabularyEntry `json:"items"`
}

// VocabularyEntryUpdate defines model for VocabularyEntryUpdate.
type VocabularyEntryUpdate struct {
	Example   *string `json:"example,omitempty"`
	ExampleVi *string `json:"example_vi,omitempty"`
	Ipa       *string `json:"ipa,omitempty"`
	Meaning   *string `json:"meaning,omitempty"`
	Word      *string `json:"word,omitempty"`
}

// VocabularyReview defines model for VocabularyReview.
type VocabularyReview struct {
	DueOn          string    `json:"due_on"`
	EaseFactor     float64   `json:"ease_factor"`
	IntervalDays   int32     `json:"interval_days"`
	LastReviewedAt time.Time `json:"last_reviewed_at"`
	Repetitions    int32     `json:"repetitions"`
}

// VocabularyReviewRequest defines model for VocabularyReviewRequest.
type VocabularyReviewRequest struct {
	Grade VocabularyReviewRequestGrade `json:"grade"`
}

// VocabularyReviewRequestGrade defines model for VocabularyReviewRequest.Grade.
type VocabularyReviewRequestGrade string

// VocabularyState `due` đến hạn ôn (kể cả từ chưa ôn lần nào), `learning` đang học,
// `mastered` khoảng cách ôn đã từ 21 ngày trở lên.
type VocabularyState string

// VocabularyStats defines model for VocabularyStats.
type VocabularyStats struct {
	DueToday    int64 `json:"due_today"`
	Learned     int64 `json:"learned"`
	Mastered    int64 `json:"mastered"`
	NewThisWeek int64 `json:"new_this_week"`
}

// CourseId defines model for CourseId.
type CourseId = string

// Cursor defines model for Cursor.
type Cursor = string

// LevelFilter Trình độ theo khung CEFR.
type LevelFilter = CourseLevel

// PageSize defines model for PageSize.
type PageSize = int32

// StatusFilter Trạng thái xuất bản.
type StatusFilter = CourseStatus

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Conflict defines model for Conflict.
type Conflict = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// NotFound defines model for NotFound.
type NotFound = Error

// TooManyRequests defines model for TooManyRequests.
type TooManyRequests = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// ListCoursesParams defines parameters for ListCourses.
type ListCoursesParams struct {
	Status *StatusFilter `form:"status,omitempty" json:"status,omitempty"`
	Level  *LevelFilter  `form:"level,omitempty" json:"level,omitempty"`

	// PageSize Mặc định 20, trần 100.
	PageSize *PageSize `form:"page_size,omitempty" json:"page_size,omitempty"`

	// Cursor Chuỗi mờ lấy từ `next_cursor` của trang trước.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// ListMyVocabularyParams defines parameters for ListMyVocabulary.
type ListMyVocabularyParams struct {
	State *VocabularyState `form:"state,omitempty" json:"state,omitempty"`
}

// ListVocabularyParams defines parameters for ListVocabulary.
type ListVocabularyParams struct {
	LessonId string `form:"lesson_id" json:"lesson_id"`
}

// SignInWithGoogleJSONRequestBody defines body for SignInWithGoogle for application/json ContentType.
type SignInWithGoogleJSONRequestBody = GoogleSignInRequest

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// LogoutJSONRequestBody defines body for Logout for application/json ContentType.
type LogoutJSONRequestBody = RefreshRequest

// RefreshSessionJSONRequestBody defines body for RefreshSession for application/json ContentType.
type RefreshSessionJSONRequestBody = RefreshRequest

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = RegisterRequest

// CreateCourseJSONRequestBody defines body for CreateCourse for application/json ContentType.
type CreateCourseJSONRequestBody = CourseCreate

// UpdateCourseJSONRequestBody defines body for UpdateCourse for application/json ContentType.
type UpdateCourseJSONRequestBody = CourseUpdate

// CreateLessonJSONRequestBody defines body for CreateLesson for application/json ContentType.
type CreateLessonJSONRequestBody = LessonCreate

// ReorderLessonsJSONRequestBody defines body for ReorderLessons for application/json ContentType.
type ReorderLessonsJSONRequestBody = LessonOrder

// UpdateLessonJSONRequestBody defines body for UpdateLesson for application/json ContentType.
type UpdateLessonJSONRequestBody = LessonUpdate

// ReviewVocabularyEntryJSONRequestBody defines body for ReviewVocabularyEntry for application/json ContentType.
type ReviewVocabularyEntryJSONRequestBody = VocabularyReviewRequest

// CreateVocabularyEntryJSONRequestBody defines body for CreateVocabularyEntry for application/json ContentType.
type CreateVocabularyEntryJSONRequestBody = VocabularyEntryCreate

// UpdateVocabularyEntryJSONRequestBody defines body for UpdateVocabularyEntry for application/json ContentType.
type UpdateVocabularyEntryJSONRequestBody = VocabularyEntryUpdate
