// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"time"
)

// Defines values for CourseLevel.
const (
	A1 CourseLevel = "A1"
	A2 CourseLevel = "A2"
	B1 CourseLevel = "B1"
	B2 CourseLevel = "B2"
	C1 CourseLevel = "C1"
	C2 CourseLevel = "C2"
)

// Valid indicates whether the value is a known member of the CourseLevel enum.
func (e CourseLevel) Valid() bool {
	switch e {
	case A1:
		return true
	case A2:
		return true
	case B1:
		return true
	case B2:
		return true
	case C1:
		return true
	case C2:
		return true
	default:
		return false
	}
}

// Defines values for CourseStatus.
const (
	Draft     CourseStatus = "draft"
	Published CourseStatus = "published"
)

// Valid indicates whether the value is a known member of the CourseStatus enum.
func (e CourseStatus) Valid() bool {
	switch e {
	case Draft:
		return true
	case Published:
		return true
	default:
		return false
	}
}

// Defines values for ErrorCode.
const (
	ErrorCodeConflict         ErrorCode = "conflict"
	ErrorCodeForbidden        ErrorCode = "forbidden"
	ErrorCodeInternalError    ErrorCode = "internal_error"
	ErrorCodeMalformedBody    ErrorCode = "malformed_body"
	ErrorCodeMethodNotAllowed ErrorCode = "method_not_allowed"
	ErrorCodeNotFound         ErrorCode = "not_found"
	ErrorCodeRateLimited      ErrorCode = "rate_limited"
	ErrorCodeUnauthorized     ErrorCode = "unauthorized"
	ErrorCodeValidationError  ErrorCode = "validation_error"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case ErrorCodeConflict:
		return true
	case ErrorCodeForbidden:
		return true
	case ErrorCodeInternalError:
		return true
	case ErrorCodeMalformedBody:
		return true
	case ErrorCodeMethodNotAllowed:
		return true
	case ErrorCodeNotFound:
		return true
	case ErrorCodeRateLimited:
		return true
	case ErrorCodeUnauthorized:
		return true
	case ErrorCodeValidationError:
		return true
	default:
		return false
	}
}

// Defines values for LessonBlockKind.
const (
	Dialogue LessonBlockKind = "dialogue"
	Example  LessonBlockKind = "example"
	Note     LessonBlockKind = "note"
)

// Valid indicates whether the value is a known member of the LessonBlockKind enum.
func (e LessonBlockKind) Valid() bool {
	switch e {
	case Dialogue:
		return true
	case Example:
		return true
	case Note:
		return true
	default:
		return false
	}
}

// Defines values for PracticeKind.
const (
	Dictation      PracticeKind = "dictation"
	FillBlank      PracticeKind = "fill_blank"
	ListenChoose   PracticeKind = "listen_choose"
	ListenWrite    PracticeKind = "listen_write"
	MultipleChoice PracticeKind = "multiple_choice"
)

// Valid indicates whether the value is a known member of the PracticeKind enum.
func (e PracticeKind) Valid() bool {
	switch e {
	case Dictation:
		return true
	case FillBlank:
		return true
	case ListenChoose:
		return true
	case ListenWrite:
		return true
	case MultipleChoice:
		return true
	default:
		return false
	}
}

// Defines values for UpdateMeRequestDailyGoalXp.
const (
	UpdateMeRequestDailyGoalXpN100 UpdateMeRequestDailyGoalXp = 100
	UpdateMeRequestDailyGoalXpN20  UpdateMeRequestDailyGoalXp = 20
	UpdateMeRequestDailyGoalXpN50  UpdateMeRequestDailyGoalXp = 50
)

// Valid indicates whether the value is a known member of the UpdateMeRequestDailyGoalXp enum.
func (e UpdateMeRequestDailyGoalXp) Valid() bool {
	switch e {
	case UpdateMeRequestDailyGoalXpN100:
		return true
	case UpdateMeRequestDailyGoalXpN20:
		return true
	case UpdateMeRequestDailyGoalXpN50:
		return true
	default:
		return false
	}
}

// Defines values for UserDailyGoalXp.
const (
	UserDailyGoalXpN100 UserDailyGoalXp = 100
	UserDailyGoalXpN20  UserDailyGoalXp = 20
	UserDailyGoalXpN50  UserDailyGoalXp = 50
)

// Valid indicates whether the value is a known member of the UserDailyGoalXp enum.
func (e UserDailyGoalXp) Valid() bool {
	switch e {
	case UserDailyGoalXpN100:
		return true
	case UserDailyGoalXpN20:
		return true
	case UserDailyGoalXpN50:
		return true
	default:
		return false
	}
}

// Defines values for UserRole.
const (
	Admin   UserRole = "admin"
	Student UserRole = "student"
)

// Valid indicates whether the value is a known member of the UserRole enum.
func (e UserRole) Valid() bool {
	switch e {
	case Admin:
		return true
	case Student:
		return true
	default:
		return false
	}
}

// Defines values for VocabularyReviewRequestGrade.
const (
	Forgot     VocabularyReviewRequestGrade = "forgot"
	Remembered VocabularyReviewRequestGrade = "remembered"
)

// Valid indicates whether the value is a known member of the VocabularyReviewRequestGrade enum.
func (e VocabularyReviewRequestGrade) Valid() bool {
	switch e {
	case Forgot:
		return true
	case Remembered:
		return true
	default:
		return false
	}
}

// Defines values for VocabularyState.
const (
	Due      VocabularyState = "due"
	Learning VocabularyState = "learning"
	Mastered VocabularyState = "mastered"
	Waiting  VocabularyState = "waiting"
)

// Valid indicates whether the value is a known member of the VocabularyState enum.
func (e VocabularyState) Valid() bool {
	switch e {
	case Due:
		return true
	case Learning:
		return true
	case Mastered:
		return true
	case Waiting:
		return true
	default:
		return false
	}
}

// ChangePasswordRequest defines model for ChangePasswordRequest.
type ChangePasswordRequest struct {
	CurrentPassword string `json:"current_password"`
	NewPassword     string `json:"new_password"`
}

// Course defines model for Course.
type Course struct {
	CoverImageUrl *string   `json:"cover_image_url"`
	CreatedAt     time.Time `json:"created_at"`
	Description   string    `json:"description"`
	Id            string    `json:"id"`

	// Level Trình độ theo khung CEFR.
	Level CourseLevel `json:"level"`

	// Position Thứ tự trong bậc, do người soạn đặt.
	Position int32 `json:"position"`

	// Slug Example: ngu-phap-co-ban
	Slug string `json:"slug"`

	// Status Trạng thái xuất bản.
	Status CourseStatus `json:"status"`

	// Title Example: Ngữ pháp cơ bản
	Title     string    `json:"title"`
	UpdatedAt time.Time `json:"updated_at"`
}

// CourseCreate defines model for CourseCreate.
type CourseCreate struct {
	CoverImageUrl *string `json:"cover_image_url,omitempty"`
	Description   *string `json:"description,omitempty"`

	// Level Trình độ theo khung CEFR.
	Level CourseLevel `json:"level"`
	Slug  string      `json:"slug"`

	// Status Trạng thái xuất bản.
	Status *CourseStatus `json:"status,omitempty"`
	Title  string        `json:"title"`
}

// CourseLevel Trình độ theo khung CEFR.
type CourseLevel string

// CourseList defines model for CourseList.
type CourseList struct {
	Items []Course `json:"items"`

	// NextCursor Con trỏ cho trang kế tiếp; `null` nghĩa là đã hết.
	NextCursor *string `json:"next_cursor"`
}

// CourseOrder defines model for CourseOrder.
type CourseOrder struct {
	// CourseIds Toàn bộ id khoá của bậc đó, theo thứ tự mong muốn.
	CourseIds []string `json:"course_ids"`

	// Level Trình độ theo khung CEFR.
	Level CourseLevel `json:"level"`
}

// CourseProgress defines model for CourseProgress.
type CourseProgress struct {
	CompletedCount int64  `json:"completed_count"`
	CourseId       string `json:"course_id"`

	// LessonCount Tổng số bài chưa xoá của khoá — mẫu số của tỉ lệ.
	LessonCount int64 `json:"lesson_count"`
}

// CourseStatus Trạng thái xuất bản.
type CourseStatus string

// CourseUpdate defines model for CourseUpdate.
type CourseUpdate struct {
	CoverImageUrl *string `json:"cover_image_url,omitempty"`
	Description   *string `json:"description,omitempty"`

	// Level Trình độ theo khung CEFR.
	Level *CourseLevel `json:"level,omitempty"`
	Slug  *string      `json:"slug,omitempty"`

	// Status Trạng thái xuất bản.
	Status *CourseStatus `json:"status,omitempty"`
	Title  *string       `json:"title,omitempty"`
}

// DayActivity defines model for DayActivity.
type DayActivity struct {
	CompletedLessons int64  `json:"completed_lessons"`
	Date             string `json:"date"`
}

// Error defines model for Error.
type Error struct {
	Code ErrorCode `json:"code"`

	// Details Lỗi theo từng field, chỉ có với validation_error.
	Details *map[string]string `json:"details,omitempty"`

	// Message Câu thông báo tiếng Việt, hiển thị được cho người dùng.
	Message string `json:"message"`
}

// ErrorCode defines model for Error.Code.
type ErrorCode string

// GoogleSignInRequest defines model for GoogleSignInRequest.
type GoogleSignInRequest struct {
	// Code Authorization code Google trả về.
	Code string `json:"code"`

	// RedirectUri Đúng redirect_uri đã dùng ở bước chuyển hướng.
	RedirectUri string `json:"redirect_uri"`
}

// Lesson defines model for Lesson.
type Lesson struct {
	CourseId  string    `json:"course_id"`
	CreatedAt time.Time `json:"created_at"`
	Id        string    `json:"id"`
	Position  int32     `json:"position"`
	Slug      string    `json:"slug"`

	// Summary Đoạn dẫn ngắn hiện ngay dưới tiêu đề bài; có thể rỗng.
	Summary   string    `json:"summary"`
	Title     string    `json:"title"`
	UpdatedAt time.Time `json:"updated_at"`
}

// LessonBlock Mỗi dạng chỉ dùng một phần các trường, phần còn lại phải là chuỗi rỗng:
//
// | kind | trường bắt buộc | phải rỗng |
// | --- | --- | --- |
// | `note` | `body` | `text_en`, `text_vi`, `speaker` |
// | `example` | `text_en` | `body`, `speaker` |
// | `dialogue` | `text_en`, `speaker` | `body` |
//
// Database có ràng buộc bắt đúng hình dạng này, nên gửi sai là 400 chứ
// không phải một khối trống giữa bài.
type LessonBlock struct {
	Body string `json:"body"`

	// Id Chỉ có khi đọc; lúc ghi thì bỏ qua vì cả danh sách được thay mới.
	Id *string `json:"id,omitempty"`

	// Kind `note` là đoạn giải thích tiếng Việt, `example` là câu mẫu Anh–Việt,
	// `dialogue` giống `example` nhưng có tên người nói.
	Kind    LessonBlockKind `json:"kind"`
	Speaker string          `json:"speaker"`
	TextEn  string          `json:"text_en"`
	TextVi  string          `json:"text_vi"`
}

// LessonBlockKind `note` là đoạn giải thích tiếng Việt, `example` là câu mẫu Anh–Việt,
// `dialogue` giống `example` nhưng có tên người nói.
type LessonBlockKind string

// LessonBlockList Thay TOÀN BỘ nội dung của bài. Gửi mảng rỗng là xoá sạch nội dung — đó
// là cách duy nhất để làm việc đó, và nó có chủ đích.
type LessonBlockList struct {
	Blocks []LessonBlock `json:"blocks"`
}

// LessonCreate defines model for LessonCreate.
type LessonCreate struct {
	Slug  string `json:"slug"`
	Title string `json:"title"`
}

// LessonDetail defines model for LessonDetail.
type LessonDetail struct {
	// Blocks Nội dung bài theo đúng thứ tự hiển thị.
	Blocks    []LessonBlock `json:"blocks"`
	CourseId  string        `json:"course_id"`
	CreatedAt time.Time     `json:"created_at"`
	Id        string        `json:"id"`
	Position  int32         `json:"position"`
	Slug      string        `json:"slug"`

	// Summary Đoạn dẫn ngắn hiện ngay dưới tiêu đề bài; có thể rỗng.
	Summary   string    `json:"summary"`
	Title     string    `json:"title"`
	UpdatedAt time.Time `json:"updated_at"`

	// Vocabulary Từ vựng bài này dạy, theo thứ tự của người soạn. Trả cho mọi
	// người đọc được bài — khác với /me/vocabulary, vốn chỉ gồm từ của
	// những bài đã học xong.
	Vocabulary []VocabularyEntry `json:"vocabulary"`
}

// LessonList defines model for LessonList.
type LessonList struct {
	Items []Lesson `json:"items"`
}

// LessonOrder defines model for LessonOrder.
type LessonOrder struct {
	// LessonIds Toàn bộ id bài của khoá, theo thứ tự mong muốn.
	LessonIds []string `json:"lesson_ids"`
}

// LessonPracticeResult defines model for LessonPracticeResult.
type LessonPracticeResult struct {
	Correct int `json:"correct"`
	Total   int `json:"total"`
}

// LessonPracticeScore defines model for LessonPracticeScore.
type LessonPracticeScore struct {
	Attempts    int    `json:"attempts"`
	BestCorrect int    `json:"best_correct"`
	LessonId    string `json:"lesson_id"`
	Total       int    `json:"total"`
}

// LessonPracticeScoreList defines model for LessonPracticeScoreList.
type LessonPracticeScoreList struct {
	Items []LessonPracticeScore `json:"items"`
}

// LessonUpdate defines model for LessonUpdate.
type LessonUpdate struct {
	Slug    *string `json:"slug,omitempty"`
	Summary *string `json:"summary,omitempty"`
	Title   *string `json:"title,omitempty"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// PracticeAnswer defines model for PracticeAnswer.
type PracticeAnswer struct {
	// Answer Lựa chọn đã chọn, hoặc chuỗi đã gõ. So sánh bỏ qua hoa/thường và khoảng trắng thừa.
	Answer  string `json:"answer"`
	EntryId string `json:"entry_id"`

	// Kind `multiple_choice` chọn nghĩa; `fill_blank` gõ từ còn thiếu trong câu;
	// `listen_choose` nghe rồi chọn từ; `listen_write` nghe rồi gõ từ;
	// `dictation` nghe cả câu rồi gõ lại cả câu (chấm bỏ qua hoa/thường, dấu
	// câu và khoảng trắng thừa — sai chính tả vẫn là sai).
	Kind PracticeKind `json:"kind"`

	// LessonId Có khi câu hỏi đến từ lượt luyện trong bài (session với lesson_id).
	// Khi đó câu sai KHÔNG đụng tới lịch ôn: đây là lần gặp đầu, không
	// phải ôn.
	LessonId *string `json:"lesson_id,omitempty"`
}

// PracticeKind `multiple_choice` chọn nghĩa; `fill_blank` gõ từ còn thiếu trong câu;
// `listen_choose` nghe rồi chọn từ; `listen_write` nghe rồi gõ từ;
// `dictation` nghe cả câu rồi gõ lại cả câu (chấm bỏ qua hoa/thường, dấu
// câu và khoảng trắng thừa — sai chính tả vẫn là sai).
type PracticeKind string

// PracticeQuestion defines model for PracticeQuestion.
type PracticeQuestion struct {
	EntryId string `json:"entry_id"`

	// Hint Gợi ý thêm: nghĩa tiếng Việt với `fill_blank`, bản dịch của câu với
	// `dictation`. Rỗng với dạng khác.
	Hint string `json:"hint"`

	// Kind `multiple_choice` chọn nghĩa; `fill_blank` gõ từ còn thiếu trong câu;
	// `listen_choose` nghe rồi chọn từ; `listen_write` nghe rồi gõ từ;
	// `dictation` nghe cả câu rồi gõ lại cả câu (chấm bỏ qua hoa/thường, dấu
	// câu và khoảng trắng thừa — sai chính tả vẫn là sai).
	Kind PracticeKind `json:"kind"`

	// Level Trình độ theo khung CEFR.
	Level CourseLevel `json:"level"`

	// Options Rỗng với các dạng gõ tay (`fill_blank`, `listen_write`, `dictation`).
	Options []string `json:"options"`

	// Prompt Câu dẫn để HIỆN ra. `multiple_choice`: chính từ đó. `fill_blank`:
	// câu ví dụ đã khoét chỗ trống. Ba dạng nghe: chuỗi rỗng, câu dẫn là
	// âm thanh.
	Prompt string `json:"prompt"`

	// Speak Chữ để trình duyệt đọc lên với ba dạng nghe: từ với `listen_choose` và
	// `listen_write`, cả câu với `dictation`. Rỗng với dạng khác. Tách
	// khỏi `prompt` vì `prompt` là thứ được hiện ra.
	Speak string `json:"speak"`

	// Word Từ tiếng Anh. Với `listen_choose`, phía trước cần nó để máy đọc lên
	// — nghĩa là đáp án nằm sẵn trong trang. Đó là hệ quả không tránh
	// được khi phát âm bằng `speechSynthesis` thay vì file audio.
	Word string `json:"word"`
}

// PracticeResult defines model for PracticeResult.
type PracticeResult struct {
	Correct bool `json:"correct"`

	// Expected Đáp án đúng, trả về cả khi làm đúng để người học đối chiếu.
	Expected string `json:"expected"`

	// Penalised Câu sai đẩy từ về đầu hàng đợi ôn. Trả lời ĐÚNG không kéo dài
	// khoảng cách ôn — luyện dồn một buổi không được biến một từ vừa gặp
	// thành "thành thạo". Luôn là false với luyện tập trong bài.
	Penalised bool `json:"penalised"`
}

// PracticeSession Câu hỏi sinh tại chỗ từ vốn từ người học đã mở khoá — không có bảng câu
// hỏi nào để soạn. Chưa đủ từ thì `questions` rỗng; đó là trạng thái bình
// thường của màn hình, không phải lỗi.
type PracticeSession struct {
	Questions []PracticeQuestion `json:"questions"`
}

// ProgressHistory Bức tranh dài hạn, dùng cho màn Tiến độ. `ProgressSnapshot` trả lời
// "hôm nay thế nào", cái này trả lời "từ trước tới giờ thế nào".
type ProgressHistory struct {
	// ActiveDays Số ngày có học, đếm trong phạm vi `days`.
	ActiveDays    int64 `json:"active_days"`
	CurrentStreak int64 `json:"current_streak"`

	// Days Dải ngày liên tục kết thúc ở hôm nay, cũ trước mới sau. Ngày không
	// học vẫn có mặt với `completed_lessons` bằng 0.
	Days   []DayActivity `json:"days"`
	GoalXp int64         `json:"goal_xp"`

	// LongestStreak Dải liên tiếp dài nhất **trong phạm vi `days`**, không phải kỷ lục
	// mọi thời. Hỏi 30 ngày thì đây là "dài nhất trong 30 ngày qua".
	LongestStreak int64 `json:"longest_streak"`

	// TotalLessons Tổng số bài đã hoàn thành, tính trên cả đời chứ không giới hạn trong `days`.
	TotalLessons int64 `json:"total_lessons"`
	TotalXp      int64 `json:"total_xp"`
	XpPerLesson  int64 `json:"xp_per_lesson"`
}

// ProgressSnapshot defines model for ProgressSnapshot.
type ProgressSnapshot struct {
	// CompletedLessonIds Id các bài đã đánh dấu xong, mới nhất trước.
	CompletedLessonIds []string         `json:"completed_lesson_ids"`
	Courses            []CourseProgress `json:"courses"`

	// GoalXp Mục tiêu XP mỗi ngày.
	GoalXp int64 `json:"goal_xp"`

	// LatestCourseId Khoá được học gần đây nhất; `null` khi chưa học bài nào.
	LatestCourseId *string `json:"latest_course_id"`

	// StreakDays Số ngày học liên tiếp. Vẫn giữ nguyên khi hôm nay chưa học nhưng
	// hôm qua có — người học còn nguyên hôm nay để nối tiếp.
	StreakDays int64 `json:"streak_days"`

	// TodayXp XP đã đạt hôm nay, tính theo giờ Việt Nam.
	TodayXp int64 `json:"today_xp"`

	// Week Bảy ngày gần nhất, cũ trước mới sau; ngày không học vẫn có mặt.
	Week []DayActivity `json:"week"`

	// XpPerLesson XP cho mỗi bài hoàn thành. Có mặt để phía trước cộng trừ được ngay
	// khi người học bấm, mà không phải viết cứng lại con số của server.
	XpPerLesson int64 `json:"xp_per_lesson"`
}

// RefreshRequest defines model for RefreshRequest.
type RefreshRequest struct {
	RefreshToken string `json:"refresh_token"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	DisplayName string `json:"display_name"`
	Email       string `json:"email"`

	// Password Tối thiểu 12 ký tự.
	Password string `json:"password"`
}

// TokenPair defines model for TokenPair.
type TokenPair struct {
	// AccessToken JWT HS256 dùng cho header Authorization.
	AccessToken string `json:"access_token"`

	// ExpiresIn Số giây còn hiệu lực của access token.
	ExpiresIn int64 `json:"expires_in"`

	// RefreshToken Chuỗi mờ, chỉ dùng được một lần.
	RefreshToken string `json:"refresh_token"`
	User         User   `json:"user"`
}

// UpdateMeRequest defines model for UpdateMeRequest.
type UpdateMeRequest struct {
	DailyGoalXp *UpdateMeRequestDailyGoalXp `json:"daily_goal_xp,omitempty"`
	DisplayName *string                     `json:"display_name,omitempty"`
}

// UpdateMeRequestDailyGoalXp defines model for UpdateMeRequest.DailyGoalXp.
type UpdateMeRequestDailyGoalXp int

// User defines model for User.
type User struct {
	CreatedAt time.Time `json:"created_at"`

	// DailyGoalXp Mục tiêu XP mỗi ngày.
	DailyGoalXp UserDailyGoalXp `json:"daily_goal_xp"`
	DisplayName string          `json:"display_name"`
	Email       string          `json:"email"`

	// HasPassword false với tài khoản chỉ đăng nhập bằng Google — không có mật khẩu để đổi.
	HasPassword bool     `json:"has_password"`
	Id          string   `json:"id"`
	Role        UserRole `json:"role"`
}

// UserDailyGoalXp Mục tiêu XP mỗi ngày.
type UserDailyGoalXp int

// UserRole defines model for UserRole.
type UserRole string

// VocabularyCard defines model for VocabularyCard.
type VocabularyCard struct {
	Entry VocabularyEntry `json:"entry"`

	// Familiarity Số đốt sáng trên vạch 5 đốt.
	Familiarity int32 `json:"familiarity"`

	// Level Trình độ theo khung CEFR.
	Level CourseLevel `json:"level"`

	// Review `null` khi người học chưa ôn từ này lần nào.
	Review *VocabularyReview `json:"review"`

	// State `due` đến hạn ôn, `learning` đang học, `mastered` khoảng cách ôn đã từ
	// 21 ngày trở lên, `waiting` từ mới chưa tới lượt. Mỗi ngày tối đa 20 từ
	// chưa ôn lần nào được vào nhóm `due`; phần còn lại là `waiting` và lần
	// lượt vào hàng đợi những ngày sau, theo thứ tự đã học.
	State VocabularyState `json:"state"`
}

// VocabularyCardList defines model for VocabularyCardList.
type VocabularyCardList struct {
	Items []VocabularyCard `json:"items"`
}

// VocabularyEntry defines model for VocabularyEntry.
type VocabularyEntry struct {
	CreatedAt time.Time `json:"created_at"`
	Example   string    `json:"example"`
	ExampleVi string    `json:"example_vi"`
	Id        string    `json:"id"`
	Ipa       string    `json:"ipa"`
	LessonId  string    `json:"lesson_id"`
	Meaning   string    `json:"meaning"`
	Position  int32     `json:"position"`
	UpdatedAt time.Time `json:"updated_at"`
	Word      string    `json:"word"`
}

// VocabularyEntryCreate defines model for VocabularyEntryCreate.
type VocabularyEntryCreate struct {
	Example   *string `json:"example,omitempty"`
	ExampleVi *string `json:"example_vi,omitempty"`
	Ipa       *string `json:"ipa,omitempty"`
	LessonId  string  `json:"lesson_id"`
	Meaning   string  `json:"meaning"`
	Word      string  `json:"word"`
}

// VocabularyEntryList defines model for VocabularyEntryList.
type VocabularyEntryList struct {
	Items []VocabularyEntry `json:"items"`
}

// VocabularyEntryUpdate defines model for VocabularyEntryUpdate.
type VocabularyEntryUpdate struct {
	Example   *string `json:"example,omitempty"`
	ExampleVi *string `json:"example_vi,omitempty"`
	Ipa       *string `json:"ipa,omitempty"`
	Meaning   *string `json:"meaning,omitempty"`
	Word      *string `json:"word,omitempty"`
}

// VocabularyReview defines model for VocabularyReview.
type VocabularyReview struct {
	DueOn          string    `json:"due_on"`
	EaseFactor     float64   `json:"ease_factor"`
	IntervalDays   int32     `json:"interval_days"`
	LastReviewedAt time.Time `json:"last_reviewed_at"`
	Repetitions    int32     `json:"repetitions"`
}

// VocabularyReviewRequest defines model for VocabularyReviewRequest.
type VocabularyReviewRequest struct {
	Grade VocabularyReviewRequestGrade `json:"grade"`
}

// VocabularyReviewRequestGrade defines model for VocabularyReviewRequest.Grade.
type VocabularyReviewRequestGrade string

// VocabularyState `due` đến hạn ôn, `learning` đang học, `mastered` khoảng cách ôn đã từ
// 21 ngày trở lên, `waiting` từ mới chưa tới lượt. Mỗi ngày tối đa 20 từ
// chưa ôn lần nào được vào nhóm `due`; phần còn lại là `waiting` và lần
// lượt vào hàng đợi những ngày sau, theo thứ tự đã học.
type VocabularyState string

// VocabularyStats defines model for VocabularyStats.
type VocabularyStats struct {
	DueToday    int64 `json:"due_today"`
	Learned     int64 `json:"learned"`
	Mastered    int64 `json:"mastered"`
	NewThisWeek int64 `json:"new_this_week"`

	// Waiting Từ mới đã mở khoá nhưng vượt trần 20 từ mới của hôm nay.
	Waiting int64 `json:"waiting"`
}

// CourseId defines model for CourseId.
type CourseId = string

// Cursor defines model for Cursor.
type Cursor = string

// LevelFilter Trình độ theo khung CEFR.
type LevelFilter = CourseLevel

// PageSize defines model for PageSize.
type PageSize = int32

// StatusFilter Trạng thái xuất bản.
type StatusFilter = CourseStatus

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Conflict defines model for Conflict.
type Conflict = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// NotFound defines model for NotFound.
type NotFound = Error

// TooManyRequests defines model for TooManyRequests.
type TooManyRequests = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// ListCoursesParams defines parameters for ListCourses.
type ListCoursesParams struct {
	// Status Chỉ có tác dụng với token admin. Người gọi khác luôn nhận `published`,
	// và nếu xin `draft` thì nhận một trang rỗng.
	Status *StatusFilter `form:"status,omitempty" json:"status,omitempty"`
	Level  *LevelFilter  `form:"level,omitempty" json:"level,omitempty"`

	// PageSize Mặc định 20, trần 100.
	PageSize *PageSize `form:"page_size,omitempty" json:"page_size,omitempty"`

	// Cursor Chuỗi mờ lấy từ `next_cursor` của trang trước.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// GetPracticeSessionParams defines parameters for GetPracticeSession.
type GetPracticeSessionParams struct {
	// Size Số câu muốn có, mặc định 10, trần 30. Ngoài khoảng thì kẹp về biên.
	// Bỏ qua khi có lesson_id: luyện trong bài luôn hỏi hết từ của bài.
	Size *int `form:"size,omitempty" json:"size,omitempty"`

	// LessonId Luyện riêng từ của một bài, kể cả khi người học chưa bấm "Đã xong".
	// Không có thì luyện từ vốn từ đã mở khoá, ưu tiên từ đến hạn ôn.
	LessonId *string `form:"lesson_id,omitempty" json:"lesson_id,omitempty"`
}

// GetProgressHistoryParams defines parameters for GetProgressHistory.
type GetProgressHistoryParams struct {
	// Days Số ngày muốn xem, mặc định 30, trần 365. Giá trị ngoài khoảng bị
	// kẹp về biên chứ không báo lỗi — đây là tham số hiển thị, một con số
	// vô lý trên URL không đáng làm hỏng cả màn hình.
	Days *int64 `form:"days,omitempty" json:"days,omitempty"`
}

// ListMyVocabularyParams defines parameters for ListMyVocabulary.
type ListMyVocabularyParams struct {
	State *VocabularyState `form:"state,omitempty" json:"state,omitempty"`
}

// ListVocabularyParams defines parameters for ListVocabulary.
type ListVocabularyParams struct {
	LessonId string `form:"lesson_id" json:"lesson_id"`
}

// SignInWithGoogleJSONRequestBody defines body for SignInWithGoogle for application/json ContentType.
type SignInWithGoogleJSONRequestBody = GoogleSignInRequest

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// LogoutJSONRequestBody defines body for Logout for application/json ContentType.
type LogoutJSONRequestBody = RefreshRequest

// UpdateCurrentUserJSONRequestBody defines body for UpdateCurrentUser for application/json ContentType.
type UpdateCurrentUserJSONRequestBody = UpdateMeRequest

// ChangePasswordJSONRequestBody defines body for ChangePassword for application/json ContentType.
type ChangePasswordJSONRequestBody = ChangePasswordRequest

// RefreshSessionJSONRequestBody defines body for RefreshSession for application/json ContentType.
type RefreshSessionJSONRequestBody = RefreshRequest

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = RegisterRequest

// CreateCourseJSONRequestBody defines body for CreateCourse for application/json ContentType.
type CreateCourseJSONRequestBody = CourseCreate

// ReorderCoursesJSONRequestBody defines body for ReorderCourses for application/json ContentType.
type ReorderCoursesJSONRequestBody = CourseOrder

// UpdateCourseJSONRequestBody defines body for UpdateCourse for application/json ContentType.
type UpdateCourseJSONRequestBody = CourseUpdate

// CreateLessonJSONRequestBody defines body for CreateLesson for application/json ContentType.
type CreateLessonJSONRequestBody = LessonCreate

// ReorderLessonsJSONRequestBody defines body for ReorderLessons for application/json ContentType.
type ReorderLessonsJSONRequestBody = LessonOrder

// UpdateLessonJSONRequestBody defines body for UpdateLesson for application/json ContentType.
type UpdateLessonJSONRequestBody = LessonUpdate

// ReplaceLessonBlocksJSONRequestBody defines body for ReplaceLessonBlocks for application/json ContentType.
type ReplaceLessonBlocksJSONRequestBody = LessonBlockList

// CheckPracticeAnswerJSONRequestBody defines body for CheckPracticeAnswer for application/json ContentType.
type CheckPracticeAnswerJSONRequestBody = PracticeAnswer

// RecordLessonPracticeScoreJSONRequestBody defines body for RecordLessonPracticeScore for application/json ContentType.
type RecordLessonPracticeScoreJSONRequestBody = LessonPracticeResult

// ReviewVocabularyEntryJSONRequestBody defines body for ReviewVocabularyEntry for application/json ContentType.
type ReviewVocabularyEntryJSONRequestBody = VocabularyReviewRequest

// CreateVocabularyEntryJSONRequestBody defines body for CreateVocabularyEntry for application/json ContentType.
type CreateVocabularyEntryJSONRequestBody = VocabularyEntryCreate

// UpdateVocabularyEntryJSONRequestBody defines body for UpdateVocabularyEntry for application/json ContentType.
type UpdateVocabularyEntryJSONRequestBody = VocabularyEntryUpdate
