// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"time"
)

// Defines values for CourseLevel.
const (
	A1 CourseLevel = "A1"
	A2 CourseLevel = "A2"
	B1 CourseLevel = "B1"
	B2 CourseLevel = "B2"
	C1 CourseLevel = "C1"
	C2 CourseLevel = "C2"
)

// Valid indicates whether the value is a known member of the CourseLevel enum.
func (e CourseLevel) Valid() bool {
	switch e {
	case A1:
		return true
	case A2:
		return true
	case B1:
		return true
	case B2:
		return true
	case C1:
		return true
	case C2:
		return true
	default:
		return false
	}
}

// Defines values for CourseStatus.
const (
	Draft     CourseStatus = "draft"
	Published CourseStatus = "published"
)

// Valid indicates whether the value is a known member of the CourseStatus enum.
func (e CourseStatus) Valid() bool {
	switch e {
	case Draft:
		return true
	case Published:
		return true
	default:
		return false
	}
}

// Defines values for ErrorCode.
const (
	ErrorCodeConflict        ErrorCode = "conflict"
	ErrorCodeForbidden       ErrorCode = "forbidden"
	ErrorCodeInternalError   ErrorCode = "internal_error"
	ErrorCodeMalformedBody   ErrorCode = "malformed_body"
	ErrorCodeNotFound        ErrorCode = "not_found"
	ErrorCodeUnauthorized    ErrorCode = "unauthorized"
	ErrorCodeValidationError ErrorCode = "validation_error"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case ErrorCodeConflict:
		return true
	case ErrorCodeForbidden:
		return true
	case ErrorCodeInternalError:
		return true
	case ErrorCodeMalformedBody:
		return true
	case ErrorCodeNotFound:
		return true
	case ErrorCodeUnauthorized:
		return true
	case ErrorCodeValidationError:
		return true
	default:
		return false
	}
}

// Defines values for UserRole.
const (
	Admin   UserRole = "admin"
	Student UserRole = "student"
)

// Valid indicates whether the value is a known member of the UserRole enum.
func (e UserRole) Valid() bool {
	switch e {
	case Admin:
		return true
	case Student:
		return true
	default:
		return false
	}
}

// Course defines model for Course.
type Course struct {
	CoverImageUrl *string   `json:"cover_image_url"`
	CreatedAt     time.Time `json:"created_at"`
	Description   string    `json:"description"`
	Id            string    `json:"id"`

	// Level Trình độ theo khung CEFR.
	Level CourseLevel `json:"level"`

	// Slug Example: ngu-phap-co-ban
	Slug string `json:"slug"`

	// Status Trạng thái xuất bản.
	Status CourseStatus `json:"status"`

	// Title Example: Ngữ pháp cơ bản
	Title     string    `json:"title"`
	UpdatedAt time.Time `json:"updated_at"`
}

// CourseCreate defines model for CourseCreate.
type CourseCreate struct {
	CoverImageUrl *string `json:"cover_image_url,omitempty"`
	Description   *string `json:"description,omitempty"`

	// Level Trình độ theo khung CEFR.
	Level CourseLevel `json:"level"`
	Slug  string      `json:"slug"`

	// Status Trạng thái xuất bản.
	Status *CourseStatus `json:"status,omitempty"`
	Title  string        `json:"title"`
}

// CourseLevel Trình độ theo khung CEFR.
type CourseLevel string

// CourseList defines model for CourseList.
type CourseList struct {
	Items []Course `json:"items"`

	// NextCursor Con trỏ cho trang kế tiếp; `null` nghĩa là đã hết.
	NextCursor *string `json:"next_cursor"`
}

// CourseProgress defines model for CourseProgress.
type CourseProgress struct {
	CompletedCount int64  `json:"completed_count"`
	CourseId       string `json:"course_id"`

	// LessonCount Tổng số bài chưa xoá của khoá — mẫu số của tỉ lệ.
	LessonCount int64 `json:"lesson_count"`
}

// CourseStatus Trạng thái xuất bản.
type CourseStatus string

// CourseUpdate defines model for CourseUpdate.
type CourseUpdate struct {
	CoverImageUrl *string `json:"cover_image_url,omitempty"`
	Description   *string `json:"description,omitempty"`

	// Level Trình độ theo khung CEFR.
	Level *CourseLevel `json:"level,omitempty"`
	Slug  *string      `json:"slug,omitempty"`

	// Status Trạng thái xuất bản.
	Status *CourseStatus `json:"status,omitempty"`
	Title  *string       `json:"title,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Code ErrorCode `json:"code"`

	// Details Lỗi theo từng field, chỉ có với validation_error.
	Details *map[string]string `json:"details,omitempty"`

	// Message Câu thông báo tiếng Việt, hiển thị được cho người dùng.
	Message string `json:"message"`
}

// ErrorCode defines model for Error.Code.
type ErrorCode string

// Lesson defines model for Lesson.
type Lesson struct {
	CourseId  string    `json:"course_id"`
	CreatedAt time.Time `json:"created_at"`
	Id        string    `json:"id"`
	Position  int32     `json:"position"`
	Slug      string    `json:"slug"`
	Title     string    `json:"title"`
	UpdatedAt time.Time `json:"updated_at"`
}

// LessonCreate defines model for LessonCreate.
type LessonCreate struct {
	Slug  string `json:"slug"`
	Title string `json:"title"`
}

// LessonList defines model for LessonList.
type LessonList struct {
	Items []Lesson `json:"items"`
}

// LessonOrder defines model for LessonOrder.
type LessonOrder struct {
	// LessonIds Toàn bộ id bài của khoá, theo thứ tự mong muốn.
	LessonIds []string `json:"lesson_ids"`
}

// LessonUpdate defines model for LessonUpdate.
type LessonUpdate struct {
	Slug  *string `json:"slug,omitempty"`
	Title *string `json:"title,omitempty"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// ProgressSnapshot defines model for ProgressSnapshot.
type ProgressSnapshot struct {
	// CompletedLessonIds Id các bài đã đánh dấu xong, mới nhất trước.
	CompletedLessonIds []string         `json:"completed_lesson_ids"`
	Courses            []CourseProgress `json:"courses"`

	// LatestCourseId Khoá được học gần đây nhất; `null` khi chưa học bài nào.
	LatestCourseId *string `json:"latest_course_id"`
}

// RefreshRequest defines model for RefreshRequest.
type RefreshRequest struct {
	RefreshToken string `json:"refresh_token"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	DisplayName string `json:"display_name"`
	Email       string `json:"email"`

	// Password Tối thiểu 12 ký tự.
	Password string `json:"password"`
}

// TokenPair defines model for TokenPair.
type TokenPair struct {
	// AccessToken JWT HS256 dùng cho header Authorization.
	AccessToken string `json:"access_token"`

	// ExpiresIn Số giây còn hiệu lực của access token.
	ExpiresIn int64 `json:"expires_in"`

	// RefreshToken Chuỗi mờ, chỉ dùng được một lần.
	RefreshToken string `json:"refresh_token"`
	User         User   `json:"user"`
}

// User defines model for User.
type User struct {
	CreatedAt   time.Time `json:"created_at"`
	DisplayName string    `json:"display_name"`
	Email       string    `json:"email"`
	Id          string    `json:"id"`
	Role        UserRole  `json:"role"`
}

// UserRole defines model for UserRole.
type UserRole string

// CourseId defines model for CourseId.
type CourseId = string

// Cursor defines model for Cursor.
type Cursor = string

// LevelFilter Trình độ theo khung CEFR.
type LevelFilter = CourseLevel

// PageSize defines model for PageSize.
type PageSize = int32

// StatusFilter Trạng thái xuất bản.
type StatusFilter = CourseStatus

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Conflict defines model for Conflict.
type Conflict = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// ListCoursesParams defines parameters for ListCourses.
type ListCoursesParams struct {
	Status *StatusFilter `form:"status,omitempty" json:"status,omitempty"`
	Level  *LevelFilter  `form:"level,omitempty" json:"level,omitempty"`

	// PageSize Mặc định 20, trần 100.
	PageSize *PageSize `form:"page_size,omitempty" json:"page_size,omitempty"`

	// Cursor Chuỗi mờ lấy từ `next_cursor` của trang trước.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// LogoutJSONRequestBody defines body for Logout for application/json ContentType.
type LogoutJSONRequestBody = RefreshRequest

// RefreshSessionJSONRequestBody defines body for RefreshSession for application/json ContentType.
type RefreshSessionJSONRequestBody = RefreshRequest

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = RegisterRequest

// CreateCourseJSONRequestBody defines body for CreateCourse for application/json ContentType.
type CreateCourseJSONRequestBody = CourseCreate

// UpdateCourseJSONRequestBody defines body for UpdateCourse for application/json ContentType.
type UpdateCourseJSONRequestBody = CourseUpdate

// CreateLessonJSONRequestBody defines body for CreateLesson for application/json ContentType.
type CreateLessonJSONRequestBody = LessonCreate

// ReorderLessonsJSONRequestBody defines body for ReorderLessons for application/json ContentType.
type ReorderLessonsJSONRequestBody = LessonOrder

// UpdateLessonJSONRequestBody defines body for UpdateLesson for application/json ContentType.
type UpdateLessonJSONRequestBody = LessonUpdate
