// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: course.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const courseExists = `-- name: CourseExists :one
SELECT EXISTS (
    SELECT 1 FROM courses WHERE id = $1 AND deleted_at IS NULL
)
`

func (q *Queries) CourseExists(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, courseExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createCourse = `-- name: CreateCourse :one
INSERT INTO courses (slug, title, description, level, status, cover_image_url)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, slug, title, description, level, status, cover_image_url, created_at, updated_at, deleted_at
`

type CreateCourseParams struct {
	Slug          string
	Title         string
	Description   string
	Level         CourseLevel
	Status        CourseStatus
	CoverImageUrl *string
}

func (q *Queries) CreateCourse(ctx context.Context, arg CreateCourseParams) (Course, error) {
	row := q.db.QueryRow(ctx, createCourse,
		arg.Slug,
		arg.Title,
		arg.Description,
		arg.Level,
		arg.Status,
		arg.CoverImageUrl,
	)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Level,
		&i.Status,
		&i.CoverImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCourseByID = `-- name: GetCourseByID :one
SELECT id, slug, title, description, level, status, cover_image_url, created_at, updated_at, deleted_at FROM courses
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetCourseByID(ctx context.Context, id pgtype.UUID) (Course, error) {
	row := q.db.QueryRow(ctx, getCourseByID, id)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Level,
		&i.Status,
		&i.CoverImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCourseBySlug = `-- name: GetCourseBySlug :one
SELECT id, slug, title, description, level, status, cover_image_url, created_at, updated_at, deleted_at FROM courses
WHERE slug = $1 AND deleted_at IS NULL
`

func (q *Queries) GetCourseBySlug(ctx context.Context, slug string) (Course, error) {
	row := q.db.QueryRow(ctx, getCourseBySlug, slug)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Level,
		&i.Status,
		&i.CoverImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listCourses = `-- name: ListCourses :many
SELECT id, slug, title, description, level, status, cover_image_url, created_at, updated_at, deleted_at FROM courses
WHERE deleted_at IS NULL
  AND ($1::course_status IS NULL OR status = $1::course_status)
  AND ($2::course_level IS NULL OR level = $2::course_level)
  AND (
      $3::timestamptz IS NULL
      OR (created_at, id) < ($3::timestamptz, $4::uuid)
  )
ORDER BY created_at DESC, id DESC
LIMIT $5
`

type ListCoursesParams struct {
	Status          *CourseStatus
	Level           *CourseLevel
	CursorCreatedAt *time.Time
	CursorID        pgtype.UUID
	PageSize        int32
}

// Keyset pagination: con trỏ là cặp (created_at, id) của bản ghi cuối trang trước.
func (q *Queries) ListCourses(ctx context.Context, arg ListCoursesParams) ([]Course, error) {
	rows, err := q.db.Query(ctx, listCourses,
		arg.Status,
		arg.Level,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Course{}
	for rows.Next() {
		var i Course
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Description,
			&i.Level,
			&i.Status,
			&i.CoverImageUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteCourse = `-- name: SoftDeleteCourse :execrows
UPDATE courses
SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteCourse(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteCourse, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateCourse = `-- name: UpdateCourse :one
UPDATE courses
SET
    slug            = COALESCE($1, slug),
    title           = COALESCE($2, title),
    description     = COALESCE($3, description),
    level           = COALESCE($4, level),
    status          = COALESCE($5, status),
    cover_image_url = CASE
        WHEN $6::boolean THEN NULL
        ELSE COALESCE($7, cover_image_url)
    END,
    updated_at      = now()
WHERE id = $8 AND deleted_at IS NULL
RETURNING id, slug, title, description, level, status, cover_image_url, created_at, updated_at, deleted_at
`

type UpdateCourseParams struct {
	Slug            *string
	Title           *string
	Description     *string
	Level           *CourseLevel
	Status          *CourseStatus
	ClearCoverImage bool
	CoverImageUrl   *string
	ID              pgtype.UUID
}

// Mọi tham số đều optional: NULL nghĩa là giữ nguyên giá trị cũ.
func (q *Queries) UpdateCourse(ctx context.Context, arg UpdateCourseParams) (Course, error) {
	row := q.db.QueryRow(ctx, updateCourse,
		arg.Slug,
		arg.Title,
		arg.Description,
		arg.Level,
		arg.Status,
		arg.ClearCoverImage,
		arg.CoverImageUrl,
		arg.ID,
	)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Level,
		&i.Status,
		&i.CoverImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
