// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: course.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const courseExists = `-- name: CourseExists :one
SELECT EXISTS (
    SELECT 1 FROM courses WHERE id = $1 AND deleted_at IS NULL
)
`

func (q *Queries) CourseExists(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, courseExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createCourse = `-- name: CreateCourse :one
INSERT INTO courses (slug, title, description, level, status, cover_image_url, position)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    (
        SELECT coalesce(max(position) + 1, 0)
        FROM courses AS sibling
        WHERE sibling.level = $4 AND sibling.deleted_at IS NULL
    )
)
RETURNING id, slug, title, description, level, status, cover_image_url, created_at, updated_at, deleted_at, position
`

type CreateCourseParams struct {
	Slug          string
	Title         string
	Description   string
	Level         CourseLevel
	Status        CourseStatus
	CoverImageUrl *string
}

// Khoá mới đứng cuối bậc của nó, giống cách bài mới đứng cuối khoá.
func (q *Queries) CreateCourse(ctx context.Context, arg CreateCourseParams) (Course, error) {
	row := q.db.QueryRow(ctx, createCourse,
		arg.Slug,
		arg.Title,
		arg.Description,
		arg.Level,
		arg.Status,
		arg.CoverImageUrl,
	)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Level,
		&i.Status,
		&i.CoverImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Position,
	)
	return i, err
}

const getCourseByID = `-- name: GetCourseByID :one
SELECT id, slug, title, description, level, status, cover_image_url, created_at, updated_at, deleted_at, position FROM courses
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetCourseByID(ctx context.Context, id pgtype.UUID) (Course, error) {
	row := q.db.QueryRow(ctx, getCourseByID, id)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Level,
		&i.Status,
		&i.CoverImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Position,
	)
	return i, err
}

const getCourseBySlug = `-- name: GetCourseBySlug :one
SELECT id, slug, title, description, level, status, cover_image_url, created_at, updated_at, deleted_at, position FROM courses
WHERE slug = $1 AND deleted_at IS NULL
`

func (q *Queries) GetCourseBySlug(ctx context.Context, slug string) (Course, error) {
	row := q.db.QueryRow(ctx, getCourseBySlug, slug)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Level,
		&i.Status,
		&i.CoverImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Position,
	)
	return i, err
}

const listCourseIDsByLevel = `-- name: ListCourseIDsByLevel :many
SELECT id FROM courses
WHERE level = $1 AND deleted_at IS NULL
ORDER BY position, created_at, id
`

func (q *Queries) ListCourseIDsByLevel(ctx context.Context, level CourseLevel) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listCourseIDsByLevel, level)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCourses = `-- name: ListCourses :many
SELECT id, slug, title, description, level, status, cover_image_url, created_at, updated_at, deleted_at, position FROM courses
WHERE deleted_at IS NULL
  AND ($1::course_status IS NULL OR status = $1::course_status)
  AND ($2::course_level IS NULL OR level = $2::course_level)
  AND (
      $3::timestamptz IS NULL
      OR (created_at, id) < ($3::timestamptz, $4::uuid)
  )
ORDER BY created_at DESC, id DESC
LIMIT $5
`

type ListCoursesParams struct {
	Status          *CourseStatus
	Level           *CourseLevel
	CursorCreatedAt *time.Time
	CursorID        pgtype.UUID
	PageSize        int32
}

// Keyset pagination: con trỏ là cặp (created_at, id) của bản ghi cuối trang trước.
func (q *Queries) ListCourses(ctx context.Context, arg ListCoursesParams) ([]Course, error) {
	rows, err := q.db.Query(ctx, listCourses,
		arg.Status,
		arg.Level,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Course{}
	for rows.Next() {
		var i Course
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Description,
			&i.Level,
			&i.Status,
			&i.CoverImageUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reorderCourses = `-- name: ReorderCourses :execrows
UPDATE courses AS c
SET position = new_order.position, updated_at = now()
FROM (
    SELECT id, (ordinality - 1)::integer AS position
    FROM unnest($2::uuid[]) WITH ORDINALITY AS t(id, ordinality)
) AS new_order
WHERE c.id = new_order.id
  AND c.level = $1
  AND c.deleted_at IS NULL
`

type ReorderCoursesParams struct {
	Level     CourseLevel
	CourseIds []pgtype.UUID
}

// Đánh lại position theo đúng thứ tự mảng gửi lên, trong một câu. Điều kiện
// level giữ cho id của bậc khác không đổi được gì.
func (q *Queries) ReorderCourses(ctx context.Context, arg ReorderCoursesParams) (int64, error) {
	result, err := q.db.Exec(ctx, reorderCourses, arg.Level, arg.CourseIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteCourse = `-- name: SoftDeleteCourse :execrows
UPDATE courses
SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteCourse(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteCourse, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateCourse = `-- name: UpdateCourse :one
UPDATE courses AS c
SET
    slug            = COALESCE($1, c.slug),
    title           = COALESCE($2, c.title),
    description     = COALESCE($3, c.description),
    level           = COALESCE($4, c.level),
    status          = COALESCE($5, c.status),
    cover_image_url = CASE
        WHEN $6::boolean THEN NULL
        ELSE COALESCE($7, c.cover_image_url)
    END,
    -- Đổi bậc thì khoá về cuối bậc mới: position cũ là thứ tự trong bậc cũ,
    -- mang sang bậc khác thì vô nghĩa và dễ trùng với khoá đang có ở đó.
    position        = CASE
        WHEN $4 IS NOT NULL AND $4 <> c.level THEN (
            SELECT coalesce(max(position) + 1, 0)
            FROM courses AS sibling
            WHERE sibling.level = $4 AND sibling.deleted_at IS NULL
        )
        ELSE c.position
    END,
    updated_at      = now()
WHERE c.id = $8 AND c.deleted_at IS NULL
RETURNING c.id, c.slug, c.title, c.description, c.level, c.status, c.cover_image_url, c.created_at, c.updated_at, c.deleted_at, c.position
`

type UpdateCourseParams struct {
	Slug            *string
	Title           *string
	Description     *string
	Level           *CourseLevel
	Status          *CourseStatus
	ClearCoverImage bool
	CoverImageUrl   *string
	ID              pgtype.UUID
}

// Mọi tham số đều optional: NULL nghĩa là giữ nguyên giá trị cũ.
func (q *Queries) UpdateCourse(ctx context.Context, arg UpdateCourseParams) (Course, error) {
	row := q.db.QueryRow(ctx, updateCourse,
		arg.Slug,
		arg.Title,
		arg.Description,
		arg.Level,
		arg.Status,
		arg.ClearCoverImage,
		arg.CoverImageUrl,
		arg.ID,
	)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Level,
		&i.Status,
		&i.CoverImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Position,
	)
	return i, err
}
