// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lesson.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listLessonsByCourse = `-- name: ListLessonsByCourse :many
SELECT id, course_id, slug, title, position, created_at, updated_at, deleted_at FROM lessons
WHERE course_id = $1 AND deleted_at IS NULL
ORDER BY position ASC, id ASC
`

func (q *Queries) ListLessonsByCourse(ctx context.Context, courseID pgtype.UUID) ([]Lesson, error) {
	rows, err := q.db.Query(ctx, listLessonsByCourse, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Lesson{}
	for rows.Next() {
		var i Lesson
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.Slug,
			&i.Title,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
