// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lesson_practice.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listLessonPracticeScores = `-- name: ListLessonPracticeScores :many
SELECT s.lesson_id, s.best_correct, s.total, s.attempts
FROM lesson_practice_scores AS s
JOIN lessons AS l ON l.id = s.lesson_id
WHERE s.user_id = $1 AND l.deleted_at IS NULL
ORDER BY s.updated_at DESC, s.lesson_id
`

type ListLessonPracticeScoresRow struct {
	LessonID    pgtype.UUID
	BestCorrect int32
	Total       int32
	Attempts    int32
}

// Điểm của một người ở mọi bài còn sống. Bài đã xoá mềm thì điểm của nó ẩn đi.
func (q *Queries) ListLessonPracticeScores(ctx context.Context, userID pgtype.UUID) ([]ListLessonPracticeScoresRow, error) {
	rows, err := q.db.Query(ctx, listLessonPracticeScores, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLessonPracticeScoresRow{}
	for rows.Next() {
		var i ListLessonPracticeScoresRow
		if err := rows.Scan(
			&i.LessonID,
			&i.BestCorrect,
			&i.Total,
			&i.Attempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordLessonPracticeScore = `-- name: RecordLessonPracticeScore :one
INSERT INTO lesson_practice_scores (user_id, lesson_id, best_correct, total)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, lesson_id) DO UPDATE
SET best_correct = CASE
        WHEN lesson_practice_scores.total = excluded.total
            THEN GREATEST(lesson_practice_scores.best_correct, excluded.best_correct)
        ELSE excluded.best_correct
    END,
    total      = excluded.total,
    attempts   = lesson_practice_scores.attempts + 1,
    updated_at = now()
RETURNING lesson_id, best_correct, total, attempts
`

type RecordLessonPracticeScoreParams struct {
	UserID   pgtype.UUID
	LessonID pgtype.UUID
	Correct  int32
	Total    int32
}

type RecordLessonPracticeScoreRow struct {
	LessonID    pgtype.UUID
	BestCorrect int32
	Total       int32
	Attempts    int32
}

// Ghi một lượt luyện: giữ điểm cao hơn nếu cùng số câu, thay hẳn nếu số câu
// đã khác — điểm cũ tính trên một bộ từ khác, so với nó là vô nghĩa.
func (q *Queries) RecordLessonPracticeScore(ctx context.Context, arg RecordLessonPracticeScoreParams) (RecordLessonPracticeScoreRow, error) {
	row := q.db.QueryRow(ctx, recordLessonPracticeScore,
		arg.UserID,
		arg.LessonID,
		arg.Correct,
		arg.Total,
	)
	var i RecordLessonPracticeScoreRow
	err := row.Scan(
		&i.LessonID,
		&i.BestCorrect,
		&i.Total,
		&i.Attempts,
	)
	return i, err
}
