// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lesson_progress.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeLesson = `-- name: CompleteLesson :exec
INSERT INTO lesson_progress (user_id, lesson_id)
VALUES ($1, $2)
ON CONFLICT (user_id, lesson_id) DO NOTHING
`

type CompleteLessonParams struct {
	UserID   pgtype.UUID
	LessonID pgtype.UUID
}

// Idempotent: bấm "Đã xong" lần thứ hai không được dời completed_at, vì đó là
// mốc người học hoàn thành bài chứ không phải lần bấm gần nhất.
func (q *Queries) CompleteLesson(ctx context.Context, arg CompleteLessonParams) error {
	_, err := q.db.Exec(ctx, completeLesson, arg.UserID, arg.LessonID)
	return err
}

const latestCompletedCourse = `-- name: LatestCompletedCourse :one
SELECT l.course_id
FROM lesson_progress AS p
JOIN lessons AS l ON l.id = p.lesson_id
JOIN courses AS c ON c.id = l.course_id
WHERE p.user_id = $1
  AND l.deleted_at IS NULL
  AND c.deleted_at IS NULL
ORDER BY p.completed_at DESC
LIMIT 1
`

// Khoá được đụng tới gần đây nhất. Tách khỏi ListCourseProgress vì max() trên
// tập rỗng khiến sqlc không suy được kiểu; ở đây "chưa học gì" là không có hàng.
func (q *Queries) LatestCompletedCourse(ctx context.Context, userID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, latestCompletedCourse, userID)
	var course_id pgtype.UUID
	err := row.Scan(&course_id)
	return course_id, err
}

const listCompletedLessonIDs = `-- name: ListCompletedLessonIDs :many
SELECT p.lesson_id
FROM lesson_progress AS p
JOIN lessons AS l ON l.id = p.lesson_id
JOIN courses AS c ON c.id = l.course_id
WHERE p.user_id = $1
  AND l.deleted_at IS NULL
  AND c.deleted_at IS NULL
ORDER BY p.completed_at DESC
`

// Bài của khoá đã xoá mềm không còn nằm trong lộ trình nên cũng không kể tới.
func (q *Queries) ListCompletedLessonIDs(ctx context.Context, userID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listCompletedLessonIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var lesson_id pgtype.UUID
		if err := rows.Scan(&lesson_id); err != nil {
			return nil, err
		}
		items = append(items, lesson_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCourseProgress = `-- name: ListCourseProgress :many
SELECT
    c.id AS course_id,
    count(l.id)::bigint AS lesson_count,
    count(p.lesson_id)::bigint AS completed_count
FROM courses AS c
LEFT JOIN lessons AS l
    ON l.course_id = c.id AND l.deleted_at IS NULL
LEFT JOIN lesson_progress AS p
    ON p.lesson_id = l.id AND p.user_id = $1
WHERE c.deleted_at IS NULL
GROUP BY c.id
`

type ListCourseProgressRow struct {
	CourseID       pgtype.UUID
	LessonCount    int64
	CompletedCount int64
}

// Mọi khoá chưa xoá đều có mặt, kể cả khoá chưa học bài nào: phía trước cần
// biết mẫu số để vẽ tỉ lệ, không chỉ biết tử số.
func (q *Queries) ListCourseProgress(ctx context.Context, userID pgtype.UUID) ([]ListCourseProgressRow, error) {
	rows, err := q.db.Query(ctx, listCourseProgress, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCourseProgressRow{}
	for rows.Next() {
		var i ListCourseProgressRow
		if err := rows.Scan(&i.CourseID, &i.LessonCount, &i.CompletedCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDailyCompletions = `-- name: ListDailyCompletions :many
SELECT
    (p.completed_at AT TIME ZONE 'Asia/Ho_Chi_Minh')::date AS day,
    count(*)::bigint AS completions
FROM lesson_progress AS p
JOIN lessons AS l ON l.id = p.lesson_id
JOIN courses AS c ON c.id = l.course_id
WHERE p.user_id = $1
  AND l.deleted_at IS NULL
  AND c.deleted_at IS NULL
GROUP BY 1
ORDER BY 1 DESC
LIMIT 400
`

type ListDailyCompletionsRow struct {
	Day         pgtype.Date
	Completions int64
}

// Gom số bài hoàn thành theo ngày ở múi giờ Việt Nam. XP hôm nay, chuỗi ngày
// liên tiếp và bảy chấm trong tuần đều suy ra từ đúng bảng này, nên không có
// con số nào phải giữ đồng bộ bằng tay.
func (q *Queries) ListDailyCompletions(ctx context.Context, userID pgtype.UUID) ([]ListDailyCompletionsRow, error) {
	rows, err := q.db.Query(ctx, listDailyCompletions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDailyCompletionsRow{}
	for rows.Next() {
		var i ListDailyCompletionsRow
		if err := rows.Scan(&i.Day, &i.Completions); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const uncompleteLesson = `-- name: UncompleteLesson :execrows
DELETE FROM lesson_progress
WHERE user_id = $1
  AND lesson_id = $2
`

type UncompleteLessonParams struct {
	UserID   pgtype.UUID
	LessonID pgtype.UUID
}

func (q *Queries) UncompleteLesson(ctx context.Context, arg UncompleteLessonParams) (int64, error) {
	result, err := q.db.Exec(ctx, uncompleteLesson, arg.UserID, arg.LessonID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
