// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type CourseLevel string

const (
	CourseLevelA1 CourseLevel = "A1"
	CourseLevelA2 CourseLevel = "A2"
	CourseLevelB1 CourseLevel = "B1"
	CourseLevelB2 CourseLevel = "B2"
	CourseLevelC1 CourseLevel = "C1"
	CourseLevelC2 CourseLevel = "C2"
)

func (e *CourseLevel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CourseLevel(s)
	case string:
		*e = CourseLevel(s)
	default:
		return fmt.Errorf("unsupported scan type for CourseLevel: %T", src)
	}
	return nil
}

type NullCourseLevel struct {
	CourseLevel CourseLevel
	Valid       bool // Valid is true if CourseLevel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCourseLevel) Scan(value interface{}) error {
	if value == nil {
		ns.CourseLevel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CourseLevel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCourseLevel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CourseLevel), nil
}

type CourseStatus string

const (
	CourseStatusDraft     CourseStatus = "draft"
	CourseStatusPublished CourseStatus = "published"
)

func (e *CourseStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CourseStatus(s)
	case string:
		*e = CourseStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CourseStatus: %T", src)
	}
	return nil
}

type NullCourseStatus struct {
	CourseStatus CourseStatus
	Valid        bool // Valid is true if CourseStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCourseStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CourseStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CourseStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCourseStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CourseStatus), nil
}

type LessonBlockKind string

const (
	LessonBlockKindNote     LessonBlockKind = "note"
	LessonBlockKindExample  LessonBlockKind = "example"
	LessonBlockKindDialogue LessonBlockKind = "dialogue"
)

func (e *LessonBlockKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LessonBlockKind(s)
	case string:
		*e = LessonBlockKind(s)
	default:
		return fmt.Errorf("unsupported scan type for LessonBlockKind: %T", src)
	}
	return nil
}

type NullLessonBlockKind struct {
	LessonBlockKind LessonBlockKind
	Valid           bool // Valid is true if LessonBlockKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLessonBlockKind) Scan(value interface{}) error {
	if value == nil {
		ns.LessonBlockKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LessonBlockKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLessonBlockKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LessonBlockKind), nil
}

type UserRole string

const (
	UserRoleAdmin   UserRole = "admin"
	UserRoleStudent UserRole = "student"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole
	Valid    bool // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type Course struct {
	ID            pgtype.UUID
	Slug          string
	Title         string
	Description   string
	Level         CourseLevel
	Status        CourseStatus
	CoverImageUrl *string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	DeletedAt     *time.Time
	Position      int32
}

type Lesson struct {
	ID        pgtype.UUID
	CourseID  pgtype.UUID
	Slug      string
	Title     string
	Position  int32
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt *time.Time
	Summary   string
}

type LessonBlock struct {
	ID        pgtype.UUID
	LessonID  pgtype.UUID
	Kind      LessonBlockKind
	Body      string
	TextEn    string
	TextVi    string
	Speaker   string
	Position  int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

type LessonPracticeScore struct {
	UserID      pgtype.UUID
	LessonID    pgtype.UUID
	BestCorrect int32
	Total       int32
	Attempts    int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type LessonProgress struct {
	UserID      pgtype.UUID
	LessonID    pgtype.UUID
	CompletedAt time.Time
}

type RefreshToken struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	TokenHash []byte
	ExpiresAt time.Time
	RevokedAt *time.Time
	CreatedAt time.Time
}

type User struct {
	ID           pgtype.UUID
	Email        string
	PasswordHash *string
	DisplayName  string
	Role         UserRole
	CreatedAt    time.Time
	UpdatedAt    time.Time
	DeletedAt    *time.Time
	GoogleSub    *string
}

type VocabularyEntry struct {
	ID        pgtype.UUID
	LessonID  pgtype.UUID
	Word      string
	Ipa       string
	Meaning   string
	Example   string
	ExampleVi string
	Position  int32
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt *time.Time
}

type VocabularyReview struct {
	UserID         pgtype.UUID
	EntryID        pgtype.UUID
	EaseFactor     float64
	IntervalDays   int32
	Repetitions    int32
	DueOn          pgtype.Date
	LastReviewedAt time.Time
	CreatedAt      time.Time
	UpdatedAt      time.Time
}
