// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type CourseLevel string

const (
	CourseLevelA1 CourseLevel = "A1"
	CourseLevelA2 CourseLevel = "A2"
	CourseLevelB1 CourseLevel = "B1"
	CourseLevelB2 CourseLevel = "B2"
	CourseLevelC1 CourseLevel = "C1"
	CourseLevelC2 CourseLevel = "C2"
)

func (e *CourseLevel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CourseLevel(s)
	case string:
		*e = CourseLevel(s)
	default:
		return fmt.Errorf("unsupported scan type for CourseLevel: %T", src)
	}
	return nil
}

type NullCourseLevel struct {
	CourseLevel CourseLevel
	Valid       bool // Valid is true if CourseLevel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCourseLevel) Scan(value interface{}) error {
	if value == nil {
		ns.CourseLevel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CourseLevel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCourseLevel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CourseLevel), nil
}

type CourseStatus string

const (
	CourseStatusDraft     CourseStatus = "draft"
	CourseStatusPublished CourseStatus = "published"
)

func (e *CourseStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CourseStatus(s)
	case string:
		*e = CourseStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CourseStatus: %T", src)
	}
	return nil
}

type NullCourseStatus struct {
	CourseStatus CourseStatus
	Valid        bool // Valid is true if CourseStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCourseStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CourseStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CourseStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCourseStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CourseStatus), nil
}

type Course struct {
	ID            pgtype.UUID
	Slug          string
	Title         string
	Description   string
	Level         CourseLevel
	Status        CourseStatus
	CoverImageUrl *string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	DeletedAt     *time.Time
}

type Lesson struct {
	ID        pgtype.UUID
	CourseID  pgtype.UUID
	Slug      string
	Title     string
	Position  int32
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt *time.Time
}
