// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vocabulary.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countVocabularyLearnedThisWeek = `-- name: CountVocabularyLearnedThisWeek :one
SELECT count(*)::bigint FROM vocabulary_reviews
WHERE user_id = $1
  AND created_at >= now() - interval '7 days'
`

// "Từ mới tuần này" đếm theo lần ôn đầu tiên, tức là lúc hàng được tạo.
func (q *Queries) CountVocabularyLearnedThisWeek(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countVocabularyLearnedThisWeek, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createVocabularyEntry = `-- name: CreateVocabularyEntry :one
INSERT INTO vocabulary_entries (lesson_id, word, ipa, meaning, example, example_vi, position)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    (
        SELECT coalesce(max(position) + 1, 0)
        FROM vocabulary_entries
        WHERE lesson_id = $1 AND deleted_at IS NULL
    )
)
RETURNING id, lesson_id, word, ipa, meaning, example, example_vi, position, created_at, updated_at, deleted_at
`

type CreateVocabularyEntryParams struct {
	LessonID  pgtype.UUID
	Word      string
	Ipa       string
	Meaning   string
	Example   string
	ExampleVi string
}

// Từ mới luôn đứng cuối bài, giống cách bài mới đứng cuối khoá.
func (q *Queries) CreateVocabularyEntry(ctx context.Context, arg CreateVocabularyEntryParams) (VocabularyEntry, error) {
	row := q.db.QueryRow(ctx, createVocabularyEntry,
		arg.LessonID,
		arg.Word,
		arg.Ipa,
		arg.Meaning,
		arg.Example,
		arg.ExampleVi,
	)
	var i VocabularyEntry
	err := row.Scan(
		&i.ID,
		&i.LessonID,
		&i.Word,
		&i.Ipa,
		&i.Meaning,
		&i.Example,
		&i.ExampleVi,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getVocabularyEntry = `-- name: GetVocabularyEntry :one
SELECT id, lesson_id, word, ipa, meaning, example, example_vi, position, created_at, updated_at, deleted_at FROM vocabulary_entries
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetVocabularyEntry(ctx context.Context, id pgtype.UUID) (VocabularyEntry, error) {
	row := q.db.QueryRow(ctx, getVocabularyEntry, id)
	var i VocabularyEntry
	err := row.Scan(
		&i.ID,
		&i.LessonID,
		&i.Word,
		&i.Ipa,
		&i.Meaning,
		&i.Example,
		&i.ExampleVi,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getVocabularyReview = `-- name: GetVocabularyReview :one
SELECT user_id, entry_id, ease_factor, interval_days, repetitions, due_on, last_reviewed_at, created_at, updated_at FROM vocabulary_reviews
WHERE user_id = $1 AND entry_id = $2
`

type GetVocabularyReviewParams struct {
	UserID  pgtype.UUID
	EntryID pgtype.UUID
}

func (q *Queries) GetVocabularyReview(ctx context.Context, arg GetVocabularyReviewParams) (VocabularyReview, error) {
	row := q.db.QueryRow(ctx, getVocabularyReview, arg.UserID, arg.EntryID)
	var i VocabularyReview
	err := row.Scan(
		&i.UserID,
		&i.EntryID,
		&i.EaseFactor,
		&i.IntervalDays,
		&i.Repetitions,
		&i.DueOn,
		&i.LastReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listVocabularyByLesson = `-- name: ListVocabularyByLesson :many
SELECT id, lesson_id, word, ipa, meaning, example, example_vi, position, created_at, updated_at, deleted_at FROM vocabulary_entries
WHERE lesson_id = $1 AND deleted_at IS NULL
ORDER BY position, id
`

func (q *Queries) ListVocabularyByLesson(ctx context.Context, lessonID pgtype.UUID) ([]VocabularyEntry, error) {
	rows, err := q.db.Query(ctx, listVocabularyByLesson, lessonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VocabularyEntry{}
	for rows.Next() {
		var i VocabularyEntry
		if err := rows.Scan(
			&i.ID,
			&i.LessonID,
			&i.Word,
			&i.Ipa,
			&i.Meaning,
			&i.Example,
			&i.ExampleVi,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVocabularyForUser = `-- name: ListVocabularyForUser :many
SELECT
    e.id, e.lesson_id, e.word, e.ipa, e.meaning, e.example, e.example_vi,
    e.position, e.created_at, e.updated_at,
    c.level AS level,
    r.ease_factor, r.interval_days, r.repetitions, r.due_on, r.last_reviewed_at
FROM vocabulary_entries AS e
JOIN lessons AS l ON l.id = e.lesson_id
JOIN courses AS c ON c.id = l.course_id
JOIN lesson_progress AS p ON p.lesson_id = l.id AND p.user_id = $1
LEFT JOIN vocabulary_reviews AS r
    ON r.entry_id = e.id AND r.user_id = $1
WHERE e.deleted_at IS NULL
  AND l.deleted_at IS NULL
  AND c.deleted_at IS NULL
ORDER BY
    -- Chưa ôn lần nào đứng trước, rồi tới hạn cũ nhất.
    r.due_on NULLS FIRST,
    e.created_at,
    e.id
`

type ListVocabularyForUserRow struct {
	ID             pgtype.UUID
	LessonID       pgtype.UUID
	Word           string
	Ipa            string
	Meaning        string
	Example        string
	ExampleVi      string
	Position       int32
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Level          CourseLevel
	EaseFactor     *float64
	IntervalDays   *int32
	Repetitions    *int32
	DueOn          pgtype.Date
	LastReviewedAt *time.Time
}

// Toàn bộ từ thuộc những bài người này đã đánh dấu hoàn thành, kèm lịch ôn nếu
// đã có. Chưa học bài thì chưa thấy từ của bài — hàng đợi bám theo tiến độ mà
// không cần một lần ghi nào lúc học xong.
func (q *Queries) ListVocabularyForUser(ctx context.Context, userID pgtype.UUID) ([]ListVocabularyForUserRow, error) {
	rows, err := q.db.Query(ctx, listVocabularyForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVocabularyForUserRow{}
	for rows.Next() {
		var i ListVocabularyForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.LessonID,
			&i.Word,
			&i.Ipa,
			&i.Meaning,
			&i.Example,
			&i.ExampleVi,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Level,
			&i.EaseFactor,
			&i.IntervalDays,
			&i.Repetitions,
			&i.DueOn,
			&i.LastReviewedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteVocabularyEntry = `-- name: SoftDeleteVocabularyEntry :execrows
UPDATE vocabulary_entries
SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteVocabularyEntry(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteVocabularyEntry, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateVocabularyEntry = `-- name: UpdateVocabularyEntry :one
UPDATE vocabulary_entries
SET word       = coalesce($1, word),
    ipa        = coalesce($2, ipa),
    meaning    = coalesce($3, meaning),
    example    = coalesce($4, example),
    example_vi = coalesce($5, example_vi),
    updated_at = now()
WHERE id = $6 AND deleted_at IS NULL
RETURNING id, lesson_id, word, ipa, meaning, example, example_vi, position, created_at, updated_at, deleted_at
`

type UpdateVocabularyEntryParams struct {
	Word      *string
	Ipa       *string
	Meaning   *string
	Example   *string
	ExampleVi *string
	ID        pgtype.UUID
}

func (q *Queries) UpdateVocabularyEntry(ctx context.Context, arg UpdateVocabularyEntryParams) (VocabularyEntry, error) {
	row := q.db.QueryRow(ctx, updateVocabularyEntry,
		arg.Word,
		arg.Ipa,
		arg.Meaning,
		arg.Example,
		arg.ExampleVi,
		arg.ID,
	)
	var i VocabularyEntry
	err := row.Scan(
		&i.ID,
		&i.LessonID,
		&i.Word,
		&i.Ipa,
		&i.Meaning,
		&i.Example,
		&i.ExampleVi,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const upsertVocabularyReview = `-- name: UpsertVocabularyReview :one
INSERT INTO vocabulary_reviews (
    user_id, entry_id, ease_factor, interval_days, repetitions, due_on, last_reviewed_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    now()
)
ON CONFLICT (user_id, entry_id) DO UPDATE
SET ease_factor      = excluded.ease_factor,
    interval_days    = excluded.interval_days,
    repetitions      = excluded.repetitions,
    due_on           = excluded.due_on,
    last_reviewed_at = now(),
    updated_at       = now()
RETURNING user_id, entry_id, ease_factor, interval_days, repetitions, due_on, last_reviewed_at, created_at, updated_at
`

type UpsertVocabularyReviewParams struct {
	UserID       pgtype.UUID
	EntryID      pgtype.UUID
	EaseFactor   float64
	IntervalDays int32
	Repetitions  int32
	DueOn        pgtype.Date
}

func (q *Queries) UpsertVocabularyReview(ctx context.Context, arg UpsertVocabularyReviewParams) (VocabularyReview, error) {
	row := q.db.QueryRow(ctx, upsertVocabularyReview,
		arg.UserID,
		arg.EntryID,
		arg.EaseFactor,
		arg.IntervalDays,
		arg.Repetitions,
		arg.DueOn,
	)
	var i VocabularyReview
	err := row.Scan(
		&i.UserID,
		&i.EntryID,
		&i.EaseFactor,
		&i.IntervalDays,
		&i.Repetitions,
		&i.DueOn,
		&i.LastReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const vocabularyEntryUnlocked = `-- name: VocabularyEntryUnlocked :one
SELECT EXISTS (
    SELECT 1
    FROM vocabulary_entries AS e
    JOIN lessons AS l ON l.id = e.lesson_id
    JOIN courses AS c ON c.id = l.course_id
    JOIN lesson_progress AS p ON p.lesson_id = l.id AND p.user_id = $1
    WHERE e.id = $2
      AND e.deleted_at IS NULL
      AND l.deleted_at IS NULL
      AND c.deleted_at IS NULL
)::boolean
`

type VocabularyEntryUnlockedParams struct {
	UserID  pgtype.UUID
	EntryID pgtype.UUID
}

// Từ chỉ ôn được khi người học đã đánh dấu hoàn thành bài chứa nó. Kiểm bằng
// một câu thay vì tải cả danh sách về rồi dò.
func (q *Queries) VocabularyEntryUnlocked(ctx context.Context, arg VocabularyEntryUnlockedParams) (bool, error) {
	row := q.db.QueryRow(ctx, vocabularyEntryUnlocked, arg.UserID, arg.EntryID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}
